defmodule Frac5.Pixels do
  @moduledoc """
  `Frac5.Pixels` defines the function `pixelate()` for converting a
  stream of 5D points from a `Frac5.State` object into a grid of
  pixels which can be written to an image file.  Currently, the image
  file resolution is fixed to `2048 * 2048` pixels, and the scaling
  from the point space to the image frame is set such that the image
  ranges from `-2 * PI` to `2 * PI` in both `x` and `y` dimensions.
  This module also provides the utility function `rand_unit_vec()` for
  generating a randomly oriented unit vector, useful for picking a
  random `zcolor` direction, which will be projected out of the color
  space in order to limit the palette of the generated image.
  N.B. The unit vector is not truly random in orientation space;
  because the directions are chosen from the unit cube rather than a
  unit sphere, it favors picking directions biased towards the corners
  of the unit cube, which is helpful for making "nice" color schemes.
  """

  import Nx.Defn

  @doc """
  Generates a random vector in n-dimensional space, by generating
  independent uniformly distributed components in each dimension, and
  then dividing each component by the norm of the resulting vector.
  N.B. this does *not* pick an orientation randomly from the surface
  of the unit sphere, but rather, from the volume of the unit cube, so
  it is biased in favor of directions pointing toward the corners of
  the cube.
  """
  def rand_unit_vec(dim) do
    l =
      for _i <- 1..dim do
        :rand.uniform() - 0.5
      end

    norm = :math.sqrt(Enum.reduce(l, 0, fn v, sum -> sum + v * v end))

    Enum.map(l, fn v -> v / norm end)
    |> Nx.tensor()
  end

  @pi2 2.0 * :math.acos(-1.0)
  @pi4 2.0 * @pi2
  @default_resolution 2048
  @doc """
  When passed an `Nx` tensor of 5-d points, a pair of tensors
  `{grid, count}` respectively of floats and integers, with the
  shape of an RGB pixel grid with dimensions `{dim, dim}`, and
  a `zcolor` unit vector to project out of the color dimensions
  of the points, projects the `zcolor` out of the colors, finds
  the pixels into which the points fall, and adds to the `grid`
  and `count` tensors the corresponding colors and numbers of
  points, then returns the updated pair `{grid, count}`.
  """
  defn pixel_reducer(pts, {grid, count}, zcolor) do
    {dim, _dim, 1} = Nx.shape(count)
    {npts, 5} = Nx.shape(pts)
    rgbs = pts[[.., 2..4]]
    dots = Nx.dot(rgbs, zcolor)
    rgbs = rgbs - Nx.outer(dots, zcolor)
    xys = pts[[.., 0..1]]
    indices = Nx.as_type(Nx.floor(dim * (xys + @pi2) / @pi4), :s16)
    indices = Nx.clip(indices, 0, dim - 1)
    grid = Nx.indexed_add(grid, indices, rgbs)
    count = Nx.indexed_add(count, indices, Nx.broadcast(1, {npts, 1}))
    {grid, count}
  end

  @doc """
  Converts the tensors `(grid, count)` as updated by the `pixel_reducer`
  function into a `{dim, dim, 3}`-shaped tensor of bytes, suitable
  for rendering to an image file. Uses the expression
  `127.5 * (1.0 - Nx.cos(grid / count))` to generate pixel values in the
  range of unsigned bytes.
  """
  defn color_bytes(grid, count) do
    Nx.as_type(127.5 * (1.0 - Nx.cos(grid / count)), :u8)
  end

  @init_count 9

  @doc """
  Accepts a stream of point blocks as generated by
  `Frac5.State.points_stream()` and a `zcolor (r, g, b)`
  vector. Accumulates the `pts_stream` into `{grid, count}` tensors
  using the `pixel_reducer` function, and then converts the resulting
  pair of tensors into a color image tensor using the `color_bytes`
  function.
  """
  def pixelate(pts_stream, zcolor, dim \\ @default_resolution, bg_value \\ 0.0) do
    grid0 = Nx.broadcast(bg_value * @init_count, {dim, dim, 3})
    count0 = Nx.broadcast(@init_count, {dim, dim, 1})

    {grid, count} =
      Enum.reduce(pts_stream, {grid0, count0}, fn pts, {grid, count} ->
	pixel_reducer(pts, {grid, count}, zcolor)
      end)

    IO.inspect(
      Enum.sum(Nx.to_list(Nx.sum(count, axes: [1, 2]))) - @init_count * dim * dim)

    color_bytes(grid, count)
  end
end
