defmodule Frac5 do
  @moduledoc """

  `Frac5` is a modular library for generating fractals based on
  iterative transformations of points in a 5-dimensional space, where
  the five dimensions can be thought of as `(x, y, r, g, b)`.  `Frac5`
  depends on `Nx` (and an `Nx` backend library of the users' choice)
  to compute transformations on hardware efficiently. The parent
  module `Frac5` only provides an example function for generating
  one form of the fractals, leaving up to the imagination of the
  user of the library the choice of what other forms to create.

  `Frac5.Affine` handles linear transformations of points, by matrix
  multiplication, and defines a function to generate a sequence of
  such transformations, optionally interleaved with other
  transformations chosen by the programmer.

  `Frac5.Transforms` defines some helpful non-linear transformations
  as examples.

  `Frac5.Ring` defines a simple ring buffer data structure, used to
  select a transformation to apply from a sequence, such as that
  generated by the `Frac5.Affine` module

  `Frac5.State` defines a struct, which can be used to generate a
  stream of chunks of 5D points as `Nx` tensors, when given two
  sequences of transformations, one to be applied in sequence,
  the other to be applied "in parallel".

  `Frac5.Pixels` provides a function `pixelate` which accepts a
  `Frac5.State` object, generates a stream of vectors of 5-dimenaional
  points from it, and reduces them to generate a grid of pixels,
  suitable for rendering to a color image file.

  `Frac5.Pnm` provides functions for writing and reading grids of
  pixels, either color or grayscale, to or from compressed NetPBM
  `.pgm.gz` or `.ppm.gz` files, chosen because the uncompressed form
  is maximally simple to read and write (N.B. the module only supports
  the one-byte-per-channel binary format). ImageMagick or NetPBM
  software can be used to translate between these files and more
  standard formats.

  """

  @doc """
  Writes a sample image at a `path` chosen by the caller, using
  randomly generated matrices and a random `zcolor` vector.
  """
  def example_image(path, max_points \\ 1.0e6) do
    scale = 0.5 + 0.3 * :rand.uniform()
    affine_seq = Frac5.Affine.generate_seq_txforms(3, scale)
    zcolor = Frac5.Pixels.rand_unit_vec(3)
    IO.inspect(Nx.to_list(zcolor))

    grid =
      Frac5.State.new(
	Frac5.Transforms.init_points(),
        affine_seq,
        Frac5.Transforms.default_parallels(),
        max_points
      )
      |> IO.inspect()
      |> Frac5.State.points_stream()
      |> Frac5.Pixels.pixelate(zcolor)

    Frac5.Pnm.render_gz!(grid, path) |> IO.inspect()
  end
end
